### ISSUE TITLE
Replacing all _ with . in the event string is causing errors

### ISSUE THREAD

**Issue by joshontheweb** [nijikokun/stripe-mock-webhooks#1]
There are some events that have _ in them.  Such as `invoice.payment_failed` or `customer.subscription.trial_will_end`.

So it will give me errors like 
`webhooks.trigger('customer.subscription.trial_will_end')`

`Error: StripeMockWebhooks: no such webhook [customer.subscription.trial.will_end] for version [2015-10-01]`

**Comment by joshontheweb** [comment]
The _ replacing seems unnecessary anyway.  Is there a reason for this?

**Comment by nijikokun** [comment]
Yes, I agree with you, in hindsight, this was a bad idea.
